# Generated by Django 5.0.1 on 2024-05-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_appsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('img', models.ImageField(upload_to='equipment_inventory/')),
            ],
        ),
    ]
