# Generated by Django 5.0.1 on 2024-05-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_equipmentinventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentinventory',
            name='available',
        ),
        migrations.AddField(
            model_name='equipmentinventory',
            name='maintenance_status',
            field=models.CharField(choices=[('available', 'Available'), ('under_maintenance', 'Under Maintenance'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
    ]
