"""
Django settings for gms project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-35jaksp#e##rz90mvne0&uu)eh8-tishemdocv_zo=f3u6yne%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "daphne",
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    "main",
    "mathfilters"

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
ASGI_APPLICATION = "gms.asgi.application"
# WSGI_APPLICATION = 'gms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "Mughal Gym Admin",
    "site_brand": "Mughal Gym",
    "site_header": "Mughal Gym Admin",
    "order_with_respect_to": [
        "auth",
        "main",  # Assuming "main" is your main app
    ],
    "custom_links": {
        "main": [
            {
                "name": "Content Management",
                "models": [
                    "main.banners",
                    "main.service",
                    "main.gallery",
                    "main.GalleryImage",
                    "main.Page",
                    "main.Faq",
                ],
            },
            {
                "name": "Subscription Plans",
                "models": [
                    "main.SubPlan",
                    "main.SubPlanFeature",
                    # Remove "main.PlanDiscount" from here
                ],
            },
            {
                "name": "User Management",
                "models": [
                    "main.Subscriber",
                    "main.Trainer",
                    "main.UserProfile",
                ],
            },
            {
                "name": "Notifications",
                "models": [
                    "main.Notify",
                    "main.NotifUserStatus",
                    "main.TrainerNotification",
                    "main.NotifTrainerStatus",
                ],
            },
            {
                "name": "Other",
                "models": [
                    "main.Enquiry",
                    "main.AssignSubscriber",
                    "main.TrainerAchivement",
                    "main.TrainerSalary",
                    "main.TrainerMsg",
                    "main.TrainerSubscriberReport",
                    "main.AppSetting",
                    "main.EquipmentInventory",
                ],
            },
        ],
    },
    "icons": {
        "auth": "fas fa-users-cog",
        "main.banners": "fas fa-flag",
        "main.service": "fas fa-concierge-bell",
        "main.gallery": "fas fa-image",
        "main.GalleryImage": "fas fa-images",
        "main.Page": "fas fa-file-alt",
        "main.Faq": "fas fa-question",
        "main.SubPlan": "fas fa-certificate",
        "main.SubPlanFeature": "fas fa-list",
        # Remove icon for "main.PlanDiscount" if present
        "main.Subscriber": "fas fa-user",
        "main.Trainer": "fas fa-user-tie",
        "main.UserProfile": "fas fa-user-cog",
        "main.Notify": "fas fa-bell",
        "main.NotifUserStatus": "fas fa-bell",
        "main.TrainerNotification": "fas fa-bell",
        "main.NotifTrainerStatus": "fas fa-bell",
        "main.Enquiry": "fas fa-question-circle",
        "main.AssignSubscriber": "fas fa-user-plus",
        "main.TrainerAchivement": "fas fa-trophy",
        "main.TrainerSalary": "fas fa-money-check-alt",
        "main.TrainerMsg": "fas fa-comment-alt",
        "main.TrainerSubscriberReport": "fas fa-file-alt",
        "main.AppSetting": "fas fa-cogs",
        "main.EquipmentInventory": "fas fa-tools",
    },
    # Hide "main.PlanDiscount" model from appearing in the sidebar
    "hide_models": ["main.PlanDiscount"],
}
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"


EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}


from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

